version: '3.3'

services:
  kong-database:
    image: postgres:9.5
    environment:
    - POSTGRES_USER=kong
    - POSTGRES_PASSWORD=kongdb
    - POSTGRES_DB=kong
  kong:
    image: kong
    depends_on:
    - kong-database
    build:
      context: .
    ports:
    - 8001:8001
    - 8000:8000
    environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database
    - KONG_PG_DATABASE=kong
    - KONG_PG_PASSWORD=kongdb
    - KONG_ADMIN_LISTEN=0.0.0.0:8001
    - KONG_LOG_LEVEL=info
    - KONG_PROXY_ACCESS_LOG=/dev/stdout
    - KONG_ADMIN_ACCESS_LOG=/dev/stdout
    - KONG_PROXY_ERROR_LOG=/dev/stdout
    - KONG_ADMIN_ERROR_LOG=/dev/stdout
