version: '3.3'

services:
  kong:
    image: kong:2.5.0-alpine
    ports:
    - 8001:8001
    - 8000:8000
    environment:
    - KONG_ADMIN_LISTEN=0.0.0.0:8001
    - KONG_LOG_LEVEL=info
    - KONG_PROXY_ACCESS_LOG=/dev/stdout
    - KONG_ADMIN_ACCESS_LOG=/dev/stdout
    - KONG_PROXY_ERROR_LOG=/dev/stdout
    - KONG_ADMIN_ERROR_LOG=/dev/stdout
    - KONG_DATABASE=off
    - KONG_PLUGINS=bundled,path-prefix
    - KONG_DECLARATIVE_CONFIG=kong.yml
    volumes:
    - ./kong/plugins/path-prefix:/usr/local/share/lua/5.1/kong/plugins/path-prefix:ro
    - ./kong.yml:/kong.yml:ro
